[package]
name = "frame"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features= ["multipart"]}
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
serde_json = "1.0"
inky = "0.1.0"
